In [41]:
import numpy as np

In [42]:
print(np.__version__)

1.23.4


In [43]:
a=np.array([1,2,3,4])
print(a)
# this returns a tuple 
print(a.shape)
# this tells us the data type
print(a.dtype)
# tells us about dimension
print(a.ndim)
# this tells us about the number of elements
print(a.size)
# tell us about item size
# since its an array of int32 so each item is 32 bits or 4 bytes
print(a.itemsize)

#indexing it same as convential arrays a[0]

#multiplies element by element
b = a * np.array([2,0,2,3])
print(b)

[1 2 3 4]
(4,)
int32
1
4
4
[ 2  0  6 12]


In [44]:
# difference between numpy list and arrays 
a=np.array([1,2,3,4])
l = [1,2,3,4]
l.append(5)
print(l)
# a.append(4) this will fail
l += [4]
print(l)
# this is called broadcasting and isnt same as arrays  (it doesnt append)
# a+= np.array([4,4,4,4]) does the same thing as below !
a+= np.array([4])
print(a)



[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 4]
[5 6 7 8]


In [45]:
a=np.array([1,2,3,4])
l = [1,2,3,4]
# repeats the array and appends
print(l*2)
# where as for numpy it multiplies each element ( no append )
print( a * 2)
# similarly for np.log np.sqrt it behaves likes this 

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [46]:
# product differences
#dot product 
a=np.array([1,2,3])
b=np.array([1,2,3])
l1 = [1,2,3]
l2 = [1,2,3]

# in lists
dot = 0 
for i in range(len(l1)):
    dot += l1[i]*l2[i]
print(dot)

# same in numpy 
dot = np.dot(a,b)
print(dot)

# or using this method
sum1 = a*b
dot = np.sum(sum1)
print(dot)

# alternative smaller code
dot = (a*b).sum()
print(dot)

#using @
dot = a@b
print(dot)

# can convert numpy array to a list using list() 
# in terms of speed numpy is faster than normal lists 

14
14
14
14
14
